In [1]:
import pandas as pd
from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVC
from sklearn.metrics import classification_report, accuracy_score

In [2]:
df = pd.read_csv("C:\\Users\\Administrator\\Desktop\\Waseela\\Datasets\\Cancer.csv")
df.head(3)

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.8,1001.0,0.11840,0.27760,0.3001,0.14710,...,17.33,184.6,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.9,1326.0,0.08474,0.07864,0.0869,0.07017,...,23.41,158.8,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.0,1203.0,0.10960,0.15990,0.1974,0.12790,...,25.53,152.5,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,NaN

In [3]:
df.drop(['id', 'Unnamed: 32'], axis=1, inplace=True)
df.columns

Index(['diagnosis', 'radius_mean', 'texture_mean', 'perimeter_mean',
       'area_mean', 'smoothness_mean', 'compactness_mean', 'concavity_mean',
       'concave points_mean', 'symmetry_mean', 'fractal_dimension_mean',
       'radius_se', 'texture_se', 'perimeter_se', 'area_se', 'smoothness_se',
       'compactness_se', 'concavity_se', 'concave points_se', 'symmetry_se',
       'fractal_dimension_se', 'radius_worst', 'texture_worst',
       'perimeter_worst', 'area_worst', 'smoothness_worst',
       'compactness_worst', 'concavity_worst', 'concave points_worst',
       'symmetry_worst', 'fractal_dimension_worst'],
      dtype='object')

In [4]:
df['diagnosis'].unique()

array(['M', 'B'], dtype=object)

In [5]:
df['diagnosis'] = df['diagnosis'].map({'M':0, 'B':1})
df.head(2)

,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,0,17.99,10.38,122.8,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,...,25.38,17.33,184.6,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,0,20.57,17.77,132.9,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,...,24.99,23.41,158.8,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902

In [7]:
x = df.drop('diagnosis', axis=1)
corr = x.corr()
corr

,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,fractal_dimension_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
radius_mean,1.000000,0.323782,0.997855,0.987357,0.170581,0.506124,0.676764,0.822529,0.147741,-0.311631,...,0.969539,0.297008,0.965137,0.941082,0.119616,0.413463,0.526911,0.744214,0.163953,0.007066
texture_mean,0.323782,1.000000,0.329533,0.321086,-0.023389,0.236702,0.302418,0.293464,0.071401,-0.076437,...,0.352573,0.912045,0.358040,0.343546,0.077503,0.277830,0.301025,0.295316,0.105008,0.119205
perimeter_mean,0.997855,0.329533,1.000000,0.986507,0.207278,0.556936,0.716136,0.850977,0.183027,-0.261477,...,0.969476,0.303038,0.970387,0.941550,0.150549,0.455774,0.563879,0.771241,0.189115,0.051019
area_mean,0.987357,0.321086,0.986507,1.000000,0.177028,0.498502,0.685983,0.823269,0.151293,-0.283110,...,0.962746,0.287489,0.959120,0.959213,0.123523,0.390410,0.512606,0.722017,0.143570,0.003738
smoothness_mean,0.170581,-0.023389,0.207278,0.177028,1.000000,0.659123,0.521984,0.553695,0.557775,0.584792,...,0.213120,0.036072,0.238853,0.206718,0.805324,0.472468,0.434926,0.503053,0.394309,0.499316
compactness_mean,0.506124,0.236702,0.556936,0.498502,0.659123,1.000000,0.883121,0.831135,0.602641,0.565369,...,0.535315,0.248133,0.590210,0.509604,0.565541,0.865809,0.816275,0.815573,0.510223,0.687382
concavity_mean,0.676764,0.302418,0.716136,0.685983,0.521984,0.883121,1.000000,0.921391,0.500667,0.336783,...,0.688236,0.299879,0.729565,0.675987,0.448822,0.754968,0.884103,0.861323,0.409464,0.514930
concave points_mean,0.822529,0.293464,0.850977,0.823269,0.553695,0.831135,0.921391,1.000000,0.462497,0.166917,...,0.830318,0.292752,0.855923,0.809630,0.452753,0.667454,0.752399,0.910155,0.375744,0.368661
symmetry_mean,0.147741,0.071401,0.183027,0.151293,0.557775,0.602641,0.500667,0.462497,1.000000,0.479921,...,0.185728,0.090651,0.219169,0.177193,0.426675,0.473200,0.433721,0.430297,0.699826,0.438413
fractal_dimension_mean,-0.311631,-0.076437,-0.261477,-0.283110,0.584792,0.565369,0.336783,0.166917,0.479921,1.000000,...,-0.253691,-0.051269,-0.205151,-0.231854,0.504942,0.458798,0.346234,0.175325,0.334019,0.767297
radius_se,0.679090,0.275869,0.691765,0.732562,0.301467,0.497473,0.631925,0.698050,0.303379,0.000111,...,0.715065,0.194799,0.719684,0.751548,0.141919,0.287103,0.380585,0.531062,0.094543,0.049559
texture_se,-0.097317,0.386358,-0.086761,-0.066280,0.068406,0.046205,0.076218,0.021480,0.128053,0.164174,...,-0.111690,0.409003,-0.102242,-0.083195,-0.073658,-0.092439,-0.068956,-0.119638,-0.128215,-0.045655
perimeter_se,0.674172,0.281673,0.693135,0.726628,0.296092,0.548905,0.660391,0.710650,0.313893,0.039830,...,0.697201,0.200371,0.721031,0.730713,0.130054,0.341919,0.418899,0.554897,0.109930,0.085433
area_se,0.735864,0.259845,0.744983,0.800086,0.246552,0.455653,0.617427,0.690299,0.223970,-0.090170,...,0.757373,0.196497,0.761213,0.811408,0.125389,0.283257,0.385100,0.538166,0.074126,0.017539
smoothness_se,-0.222600,0.006614,-0.202694,-0.166777,0.332375,0.135299,0.098564,0.027653,0.187321,0.401964,...,-0.230691,-0.074743,-0.217304,-0.182195,0.314457,-0.055558,-0.058298,-0.102007,-0.107342,0.101480
compactness_se,0.206000,0.191975,0.250744,0.212583,0.318943,0.738722,0.670279,0.490424,0.421659,0.559837,...,0.204607,0.143003,0.260516,0.199371,0.227394,0.678780,0.639147,0.483208,0.277878,0.590973
concavity_se,0.194204,0.143293,0.228082,0.207660,0.248396,0.570517,0.691270,0.439167,0.342627,0.446630,...,0.186904,0.100241,0.226680,0.188353,0.168481,0.484858,0.662564,0.440472,0.197788,0.439329
concave points_se,0.376169,0.163851,0.407217,0.372320,0.380676,0.642262,0.683260,0.615634,0.393298,0.341198,...,0.358127,0.086741,0.394999,0.342271,0.215351,0.452888,0.549592,0.602450,0.143116,0.310655
symmetry_se,-0.104321,0.009127,-0.081629,-0.072497,0.200774,0.229977,0.178009,0.095351,0.449137,0.345007,...,-0.128121,-0.077473,-0.103753,-0.110343,-0.012662,0.060255,0.037119,-0.030413,0.389402,0.078079
fractal_dimension_se,-0.042641,0.054458,-0.005523,-0.019887,0.283607,0.507318,0.449301,0.257584,0.331786,0.688132,...,-0.037488,-0.003195,-0.001000,-0.022736,0.170568,0.390159,0.379975,0.215204,0.111094,0.591328
radius_worst,0.969539,0.352573,0.969476,0.962746,0.213120,0.535315,0.688236,0.830318,0.185728,-0.253691,...,1.000000,0.359921,0.993708,0.984015,0.216574,0.475820,0.573975,0.787424,0.243529,0.093492
texture_worst,0.297008,0.912045,0.303038,0.287489,0.036072,0.248133,0.299879,0.292752,0.090651,-0.051269,...,0.359921,1.000000,0.365098,0.345842,0.225429,0.360832,0.368366,0.359755,0.233027,0.219122
perimeter_worst,0.965137,0.358040,0.970387,0.959120,0.238853,0.590210,0.729565,0.855923,0.219169,-0.205151,...,0.993708,0.365098,1.000000,0.977578,0.236775,0.529408,0.618344,0.816322,0.269493,0.138957
area_worst,0.941082,0.343546,0.941550,0.959213,0.206718,0.509604,0.675987,0.809630,0.177193,-0.231854,...,0.984015,0.345842,0.977578,1.000000,0.209145,0.438296,0.543331,0.747419,0.209146,0.079647
smoothness_worst,0.119616,0.077503,0.150549,0.123523,0.805324,0.565541,0.448822,0.452753,0.426675,0.504942,...,0.216574,0.225429,0.236775,0.209145,1.000000,0.568187,0.518523,0.547691,0.493838,0.617624
compactness_worst,0.413463,0.277830,0.455774,0.390410,0.472468,0.865809,0.754968,0.667454,0.473200,0.458798,...,0.475820,0.360832,0.529408,0.438296,0.568187,1.000000,0.892261,0.801080,0.614441,0.810455
concavity_worst,0.526911,0.301025,0.563879,0.512606,0.434926,0.816275,0.884103,0.752399,0.433721,0.346234,...,0.573975,0.368366,0.618344,0.543331,0.518523,0.892261,1.000000,0.855434,0.532520,0.686511
concave points_worst,0.744214,0.295316,0.771241,0.722017,0.503053,0.815573,0.861323,0.910155,0.430297,0.175325,...,0.787424,0.359755,0.816322,0.747419,0.547691,0.801080,0.855434,1.000000,0.502528,0.511114
symmetry_worst,0.163953,0.105008,0.189115,0.143570,0.394309,0.510223,0.409464,0.375744,0.699826,0.334019,...,0.243529,0.233027,0.269493,0.209146,0.493838,0.614441,0.532520,0.502528,1.000000,0.537848
fractal_dimension_worst,0.007066,0.119205,0.051019,0.003738,0.499316,0.687382,0.514930,0.368661,0.438413,0.767297,...,0.093492,0.219122,0.138957,0.079647,0.617624,0.810455,0.686511,0.511114,0.537848,1.000000

In [9]:
from sklearn.preprocessing import MinMaxScaler
data=['radius_mean', 'texture_mean','smoothness_mean','symmetry_mean', 
         'fractal_dimension_mean','radius_worst', 'texture_worst',
        'compactness_worst',  'symmetry_worst', 
        'fractal_dimension_worst']
scaler = MinMaxScaler()
scaled = scaler.fit_transform(df[data])

In [10]:
x = scaled
y = df['diagnosis']

In [11]:
x[:, :4]

array([[0.52103744, 0.0226581 , 0.59375282, 0.68636364],
       [0.64314449, 0.27257355, 0.28987993, 0.37979798],
       [0.60149557, 0.3902604 , 0.51430893, 0.50959596],
       ...,
       [0.45525108, 0.62123774, 0.28816467, 0.26767677],
       [0.64456434, 0.66351031, 0.58833619, 0.67525253],
       [0.03686876, 0.50152181, 0.        , 0.26616162]])

In [12]:
from sklearn.model_selection import train_test_split
x_train, x_text, y_train, y_test = train_test_split(x, y, test_size=0.2,
                                                   random_state=42)

# Support Vector Machine

In [14]:
svm = SVC(kernel='linear', C=1.0)  # You can also try 'rbf' or 'poly' kernels
svm.fit(x_train, y_train)

SVC(kernel='linear')

In [17]:
y_pred = svm.predict(x_text)

In [18]:
print("Accuracy:", accuracy_score(y_test, y_pred))
print("\nClassification Report:\n", classification_report(y_test, y_pred))

Accuracy: 0.9473684210526315

Classification Report:
               precision    recall  f1-score   support

           0       0.95      0.91      0.93        43
           1       0.95      0.97      0.96        71

    accuracy                           0.95       114
   macro avg       0.95      0.94      0.94       114
weighted avg       0.95      0.95      0.95       114

# Decision Tree

In [19]:
from sklearn.tree import DecisionTreeClassifier, plot_tree

In [21]:
tree = DecisionTreeClassifier(random_state=42)
tree.fit(x_train, y_train)
y_pred_tree = tree.predict(x_text)
print("Decision Tree Accuracy:", accuracy_score(y_test, y_pred_tree))

Decision Tree Accuracy: 0.956140350877193

In [22]:
print("\nClassification Report:\n", classification_report(y_test, y_pred))

Classification Report:
               precision    recall  f1-score   support

           0       0.95      0.91      0.93        43
           1       0.95      0.97      0.96        71

    accuracy                           0.95       114
   macro avg       0.95      0.94      0.94       114
weighted avg       0.95      0.95      0.95       114