In [62]:
import pandas as pd

In [63]:
df=pd.read_csv("C:\\Users\\Admin\\Downloads\\laptop_pricing_dataset_base.csv")
df.head(2)

   Acer  4 IPS Panel  2  1  5   35.56  1.6  8  256 1.6.1  978
0  Dell  3   Full HD  1  1  3  39.624  2.0  4  256   2.2  634
1  Dell  3   Full HD  1  1  7  39.624  2.7  8  256   2.2  946

In [64]:
df.columns

Index(['Acer', '4', 'IPS Panel', '2', '1', '5', '35.56', '1.6', '8', '256',
       '1.6.1', '978'],
      dtype='object')

In [65]:
df.shape

(237, 12)

In [66]:
df.rename(columns = {'Acer': 'manufactur',
                    '4':'GPU', 
                    'IPS Panel':'screen',
                    '2':'GPU', '1': 'OS',
                    '5':'CPU_core',
                    '35.56':'Screen_Size_cm',
                    '1.6':'CPU_frequency',
                    '8':'RAM_GB',
                    '256':'Storage_GB_SSD',
                    '1.6.1':'Weight_pounds',
                    '978':'Price'}, inplace=True)

In [67]:
df.head(2)

,manufactur,GPU,screen,GPU,OS,CPU_core,Screen_Size_cm,CPU_frequency,RAM_GB,Storage_GB_SSD,Weight_pounds,Price
0,Dell,3,Full HD,1,1,3,39.624,2.0,4,256,2.2,634
1,Dell,3,Full HD,1,1,7,39.624,2.7,8,256,2.2,946

In [68]:
df.iloc[1,3]

1

In [69]:
df.drop('GPU', axis=1, inplace=True)

In [70]:
df.head(3)

,manufactur,screen,OS,CPU_core,Screen_Size_cm,CPU_frequency,RAM_GB,Storage_GB_SSD,Weight_pounds,Price
0,Dell,Full HD,1,3,39.624,2.0,4,256,2.2,634
1,Dell,Full HD,1,7,39.624,2.7,8,256,2.2,946
2,Dell,IPS Panel,1,5,33.782,1.6,8,128,1.22,1244

In [71]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 237 entries, 0 to 236
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   manufactur      237 non-null    object
 1   screen          237 non-null    object
 2   OS              237 non-null    int64
 3   CPU_core        237 non-null    int64
 4   Screen_Size_cm  237 non-null    object
 5   CPU_frequency   237 non-null    float64
 6   RAM_GB          237 non-null    int64
 7   Storage_GB_SSD  237 non-null    int64
 8   Weight_pounds   237 non-null    object
 9   Price           237 non-null    int64
dtypes: float64(1), int64(5), object(4)
memory usage: 18.6+ KB

In [72]:
df.describe()

,OS,CPU_core,CPU_frequency,RAM_GB,Storage_GB_SSD,Price
count,237.000000,237.000000,237.000000,237.000000,237.000000,237.000000
mean,1.059072,5.632911,2.363291,7.881857,245.738397,1464.388186
std,0.236258,1.243736,0.409271,2.487845,34.832516,574.956374
min,1.000000,3.000000,1.200000,4.000000,128.000000,527.000000
25%,1.000000,5.000000,2.000000,8.000000,256.000000,1068.000000
50%,1.000000,5.000000,2.500000,8.000000,256.000000,1333.000000
75%,1.000000,7.000000,2.700000,8.000000,256.000000,1777.000000
max,2.000000,7.000000,2.900000,16.000000,256.000000,3810.000000

In [73]:
df['manufactur'].unique()

array(['Dell', 'HP', 'Acer', 'Asus', 'Lenovo', 'Huawei', 'Toshiba', 'MSI',
       'Razer', 'Samsung', 'Xiaomi'], dtype=object)

In [74]:
df['OS'].unique()

array([1, 2], dtype=int64)

In [75]:
df['manufactur'].value_counts()

manufactur
Dell       71
Lenovo     52
HP         49
Acer       18
Asus       18
Toshiba    17
Samsung     5
MSI         4
Huawei      1
Razer       1
Xiaomi      1
Name: count, dtype: int64

In [76]:
df['screen'].unique()

array(['Full HD', 'IPS Panel'], dtype=object)

In [77]:
df['screen'].value_counts()

screen
Full HD      161
IPS Panel     76
Name: count, dtype: int64

In [78]:
df['CPU_core'].unique()

array([3, 7, 5], dtype=int64)

In [79]:
df.groupby('manufactur')['screen'].unique()

manufactur
Acer       [IPS Panel, Full HD]
Asus       [Full HD, IPS Panel]
Dell       [Full HD, IPS Panel]
HP         [Full HD, IPS Panel]
Huawei              [IPS Panel]
Lenovo     [IPS Panel, Full HD]
MSI                   [Full HD]
Razer                 [Full HD]
Samsung               [Full HD]
Toshiba    [Full HD, IPS Panel]
Xiaomi              [IPS Panel]
Name: screen, dtype: object

In [80]:
df.groupby('manufactur')['screen'].value_counts()

manufactur  screen
Acer        IPS Panel    13
            Full HD       5
Asus        Full HD      16
            IPS Panel     2
Dell        Full HD      62
            IPS Panel     9
HP          Full HD      41
            IPS Panel     8
Huawei      IPS Panel     1
Lenovo      IPS Panel    32
            Full HD      20
MSI         Full HD       4
Razer       Full HD       1
Samsung     Full HD       5
Toshiba     IPS Panel    10
            Full HD       7
Xiaomi      IPS Panel     1
Name: count, dtype: int64

In [81]:
df[((df['Price']< 600) | (df['Price']==600)) ]

,manufactur,screen,OS,CPU_core,Screen_Size_cm,CPU_frequency,RAM_GB,Storage_GB_SSD,Weight_pounds,Price
10,HP,Full HD,1,3,39.624,2.0,4,128,1.91,558
11,Asus,Full HD,2,3,39.624,2.0,4,256,2,527

In [82]:
df[((df['manufactur']=='Dell') & (df['CPU_core']==7) )].head(3)

,manufactur,screen,OS,CPU_core,Screen_Size_cm,CPU_frequency,RAM_GB,Storage_GB_SSD,Weight_pounds,Price
1,Dell,Full HD,1,7,39.624,2.7,8,256,2.2,946
9,Dell,Full HD,1,7,39.624,1.8,8,256,2.13,975
15,Dell,IPS Panel,1,7,33.02,1.8,8,256,1.4,1213

In [83]:
df.groupby('manufactur')['Price'].agg(['min', 'max', 'mean'])

             min   max         mean
manufactur
Acer         727  1650  1072.111111
Asus         527  3810  1327.111111
Dell         616  3665  1495.084507
HP           558  3073  1399.285714
Huawei      1714  1714  1714.000000
Lenovo       634  3810  1493.096154
MSI         1268  1714  1452.750000
Razer       3301  3301  3301.000000
Samsung     1904  2349  2107.400000
Toshiba     1198  2509  1703.882353
Xiaomi      1188  1188  1188.000000

In [84]:
df.groupby('screen')['Screen_Size_cm'].agg(['min', 'max'])

             min    max
screen
Full HD    31.75      ?
IPS Panel  30.48  43.18

In [85]:
df[df['Screen_Size_cm'] == '?']

,manufactur,screen,OS,CPU_core,Screen_Size_cm,CPU_frequency,RAM_GB,Storage_GB_SSD,Weight_pounds,Price
119,Dell,Full HD,1,5,?,1.6,8,256,1.42,2340
150,Dell,Full HD,1,7,?,2.8,8,256,2.06,2240
186,Samsung,Full HD,1,7,?,2.7,8,256,1.31,2031
229,Dell,Full HD,1,5,?,2.5,8,256,1.36,1870

In [86]:
df[(df['manufactur']=='Dell')  & (df['screen']=='Full HD')].head(1)

,manufactur,screen,OS,CPU_core,Screen_Size_cm,CPU_frequency,RAM_GB,Storage_GB_SSD,Weight_pounds,Price
0,Dell,Full HD,1,3,39.624,2.0,4,256,2.2,634

In [87]:
df[(df['manufactur']=='Samsung')  & (df['screen']=='Full HD')].head(1)

,manufactur,screen,OS,CPU_core,Screen_Size_cm,CPU_frequency,RAM_GB,Storage_GB_SSD,Weight_pounds,Price
181,Samsung,Full HD,1,7,33.782,2.7,16,256,0.81,2095

In [88]:
df.loc[(df['manufactur'] == 'Dell') & (df['Screen_Size_cm'] == '?'),
       'Screen_Size_cm'] = 39.624

df.loc[(df['manufactur'] == 'Samsung') & (df['Screen_Size_cm'] == '?'),
       'Screen_Size_cm'] = 33.782

In [89]:
df[df['Screen_Size_cm'] == '?']

Empty DataFrame
Columns: [manufactur, screen, OS, CPU_core, Screen_Size_cm, CPU_frequency, RAM_GB, Storage_GB_SSD, Weight_pounds, Price]
Index: []

manufactur        0
screen            0
OS                0
CPU_core          0
Screen_Size_cm    0
CPU_frequency     0
RAM_GB            0
Storage_GB_SSD    0
Weight_pounds     0
Price             0
dtype: int64

In [27]:
df.groupby('manufactur')['screen'].value_counts()

manufactur  screen
Acer        IPS Panel    13
            Full HD       5
Asus        Full HD      16
            IPS Panel     2
Dell        Full HD      62
            IPS Panel     9
HP          Full HD      41
            IPS Panel     8
Huawei      IPS Panel     1
Lenovo      IPS Panel    32
            Full HD      20
MSI         Full HD       4
Razer       Full HD       1
Samsung     Full HD       5
Toshiba     IPS Panel    10
            Full HD       7
Xiaomi      IPS Panel     1
Name: count, dtype: int64