In [3]:
from google.colab import files
upload = files.upload()

Saving Student_Performance.csv to Student_Performance.csv

In [4]:
import pandas as pd

In [5]:
df = pd.read_csv('Student_Performance.csv')
df.head()

,Hours Studied,Previous Scores,Extracurricular Activities,Sleep Hours,Sample Question Papers Practiced,Performance Index
0,7,99,Yes,9,1,91.0
1,4,82,No,4,2,65.0
2,8,51,Yes,7,2,45.0
3,5,52,Yes,5,2,36.0
4,7,75,No,8,5,66.0

In [6]:
df.shape

(10000, 6)

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 6 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   Hours Studied                     10000 non-null  int64
 1   Previous Scores                   10000 non-null  int64
 2   Extracurricular Activities        10000 non-null  object
 3   Sleep Hours                       10000 non-null  int64
 4   Sample Question Papers Practiced  10000 non-null  int64
 5   Performance Index                 10000 non-null  float64
dtypes: float64(1), int64(4), object(1)
memory usage: 468.9+ KB

In [9]:
df.describe()

,Hours Studied,Previous Scores,Sleep Hours,Sample Question Papers Practiced,Performance Index
count,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000
mean,4.992900,69.445700,6.530600,4.583300,55.224800
std,2.589309,17.343152,1.695863,2.867348,19.212558
min,1.000000,40.000000,4.000000,0.000000,10.000000
25%,3.000000,54.000000,5.000000,2.000000,40.000000
50%,5.000000,69.000000,7.000000,5.000000,55.000000
75%,7.000000,85.000000,8.000000,7.000000,71.000000
max,9.000000,99.000000,9.000000,9.000000,100.000000

In [11]:
col = df.select_dtypes(include='number').columns

Index(['Hours Studied', 'Previous Scores', 'Sleep Hours',
       'Sample Question Papers Practiced', 'Performance Index'],
      dtype='object')

In [13]:
df[col].corr()

,Hours Studied,Previous Scores,Sleep Hours,Sample Question Papers Practiced,Performance Index
Hours Studied,1.000000,-0.012390,0.001245,0.017463,0.373730
Previous Scores,-0.012390,1.000000,0.005944,0.007888,0.915189
Sleep Hours,0.001245,0.005944,1.000000,0.003990,0.048106
Sample Question Papers Practiced,0.017463,0.007888,0.003990,1.000000,0.043268
Performance Index,0.373730,0.915189,0.048106,0.043268,1.000000

In [17]:
from sklearn.preprocessing import StandardScaler, LabelEncoder

In [ ]:
colum = df.select_dtypes(include='number').columns
colum

In [19]:
col = ['Hours Studied', 'Previous Scores', 'Sleep Hours','Sample Question Papers Practiced']
scaler = StandardScaler()
df[col] = scaler.fit_transform(df[col])
df.head()

,Hours Studied,Previous Scores,Extracurricular Activities,Sleep Hours,Sample Question Papers Practiced,Performance Index
0,0.775188,1.704176,1,1.456205,-1.249754,91.0
1,-0.383481,0.723913,0,-1.492294,-0.900982,65.0
2,1.161410,-1.063626,1,0.276805,-0.900982,45.0
3,0.002742,-1.005963,1,-0.902594,-0.900982,36.0
4,0.775188,0.320275,0,0.866505,0.145333,66.0

In [18]:
col1 = df.select_dtypes(include='object').columns
col1

Index([], dtype='object')

In [16]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
df['Extracurricular Activities'] = le.fit_transform(df['Extracurricular Activities'])
df.head()

,Hours Studied,Previous Scores,Extracurricular Activities,Sleep Hours,Sample Question Papers Practiced,Performance Index
0,0.775188,1.704176,1,1.456205,-1.249754,91.0
1,-0.383481,0.723913,0,-1.492294,-0.900982,65.0
2,1.161410,-1.063626,1,0.276805,-0.900982,45.0
3,0.002742,-1.005963,1,-0.902594,-0.900982,36.0
4,0.775188,0.320275,0,0.866505,0.145333,66.0

In [20]:
x = df.drop('Performance Index', axis=1)
y = df['Performance Index']

In [25]:
from sklearn.model_selection import train_test_split

In [26]:
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size=0.3, random_state=42)

In [28]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.tree import DecisionTreeRegressor
from sklearn.svm import SVC, SVR

In [29]:
from sklearn.linear_model import LinearRegression

Linear Regression

In [31]:
lr = LinearRegression()
lr.fit(x_train, y_train)
lr_pred = lr.predict(x_test)

In [32]:
from sklearn.metrics import mean_squared_error, r2_score

In [33]:
mse = mean_squared_error(y_test, lr_pred)
r2 = r2_score(y_test, lr_pred)
print('MSE = ', mse)
print('R2 Score = ', r2)

MSE =  4.066563824092683
R2 Score =  0.9890110607021136

DecisionTree

In [34]:
dt = DecisionTreeRegressor()
dt.fit(x_train, y_train)
dt_pred = dt.predict(x_test)

In [35]:
mse = mean_squared_error(y_test, dt_pred)
r2 = r2_score(y_test, dt_pred)
print('MSE = ', mse)
print('R2 Score = ', r2)

MSE =  8.866962962962964
R2 Score =  0.9760391027974714

# Random Forest

In [36]:
rf = RandomForestRegressor()
rf.fit(x_train, y_train)
rf_pred = rf.predict(x_test)

In [37]:
mse = mean_squared_error(y_test, rf_pred)
r2 = r2_score(y_test, rf_pred)
print('MSE = ', mse)
print('R2 Score = ', r2)

MSE =  5.271248547183453
R2 Score =  0.9857556815004632

Support Vector Regressor

In [38]:
svr = SVR()
svr.fit(x_train, y_train)
svr_pred = svr.predict(x_test)

In [40]:
mse = mean_squared_error(y_test, svr_pred)
print("Mean Squared Error:", mse)
r2 = r2_score(y_test, svr_pred)
print("R-squared Score:", r2)

Mean Squared Error: 5.426481306972324
R-squared Score: 0.9853362012099396

In [41]:
from sklearn.metrics import accuracy_score, precision_score, confusion_matrix